apiVersion: apps/v1
kind: Deployment
metadata:
  name: chessrs-service
  labels:
    app: chessrs-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chessrs-service
  template:
    metadata:
      labels:
        app: chessrs-service
    spec:
      containers:
        - name: chessrs-service
          image: zackmurry/chessrs-service:latest
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /api/v1/actuator/health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 60
          readinessProbe:
            httpGet:
              path: /api/v1/actuator/health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 60
          imagePullPolicy: Always
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: docker

