spring:
  application:
    name: chessrs-engine
server:
  servlet:
    context-path: /api/v1/engine
  port: 8081
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
app:
  engine:
    stockfish-path: /usr/games/stockfish

