app:
  datasource:
    jdbc-url: jdbc:postgresql://localhost:5432/chessrs
    username: ${POSTGRES_USERNAME} # PostgreSQL username
    password: ${POSTGRES_PASSWORD} # PostgreSQL password
    pool-size: 30
  auth:
    token-secret: ${CHESSRS_JWT_SECRET_KEY}
spring:
  flyway:
    baseline-on-migrate: true
  security:
    oauth2:
      client:
        registration:
          lichess:
            client-id: ${CHESSRS_LICHESS_CLIENT_ID}
            client-secret: ${CHESSRS_LICHESS_CLIENT_SECRET}
            redirect-uri: http://localhost/api/v1/oauth2/callback/lichess
            authorization-grant-type: authorization_code
        provider:
          lichess:
            authorization-uri: https://oauth.lichess.org/oauth/authorize
            token-uri: https://oauth.lichess.org/oauth
            user-info-uri: https://lichess.org/api/account
            user-name-attribute: username
logging:
  level:
    org:
      springframework:
        security: DEBUG
