app:
  datasource:
    jdbc-url: jdbc:postgresql://postgres:5432/chessrs
    username: postgres
    password: greSQLdb
    pool-size: 30
  engine:
    url: http://engine-service:8081/api/v1/engine/analyze
spring:
  flyway:
    baseline-on-migrate: true
  security:
    oauth2:
      client:
        registration:
          lichess:
            client-id: chessrs.zackmurry.com
            redirect-uri: http://localhost/api/v1/oauth2/callback/lichess
            authorization-grant-type: authorization_code
            client-authentication-method: none
        provider:
          lichess:
            authorization-uri: https://oauth.lichess.org/oauth
            token-uri: https://lichess.org/api/token
            user-info-uri: https://lichess.org/api/account
            user-name-attribute: username
  application:
    name: ChesSRS Docker Server
  banner:
    location: classpath:static/banner-docker.txt
  graphql:
    http:
      path: /api/v1/graphql
  data:
    redis:
      port: 6379
      host: redis
logging:
  file:
    name: backend.log
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
