app:
  datasource:
    jdbc-url: jdbc:postgresql://localhost:5432/chessrs
    username: ${POSTGRES_USERNAME} # PostgreSQL username
    password: ${POSTGRES_PASSWORD} # PostgreSQL password
    pool-size: 30
  engine:
    url: http://localhost:8081/api/v1/engine/analyze
spring:
  flyway:
    baseline-on-migrate: true
  security:
    oauth2:
      client:
        registration:
          lichess:
            client-id: chessrs.zackmurry.com
            redirect-uri: https://chessrs.zackmurry.com/api/v1/oauth2/callback/lichess
            authorization-grant-type: authorization_code
            client-authentication-method: none
        provider:
          lichess:
            authorization-uri: https://oauth.lichess.org/oauth
            token-uri: https://lichess.org/api/token
            user-info-uri: https://lichess.org/api/account
            user-name-attribute: username
  application:
    name: ChesSRS Production Server
  banner:
    location: classpath:static/banner-prod.txt
  graphql:
    http:
      path: /api/v1/graphql
  data:
    redis:
      port: 6379
      host: localhost
logging:
  file:
    name: backend.log
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
