app:
  datasource:
    jdbc-url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME} # PostgreSQL username
    password: ${SPRING_DATASOURCE_PASSWORD} # PostgreSQL password
    pool-size: 30
spring:
  flyway:
    baseline-on-migrate: true
  security:
    oauth2:
      client:
        registration:
          lichess:
            client-id: chessrs.zackmurry.com
            redirect-uri: http://localhost/api/v1/oauth2/callback/lichess
            authorization-grant-type: authorization_code
            client-authentication-method: none
        provider:
          lichess:
            authorization-uri: https://oauth.lichess.org/oauth
            token-uri: https://lichess.org/api/token
            user-info-uri: https://lichess.org/api/account
            user-name-attribute: username
  application:
    name: ChesSRS Docker Server
  banner:
    location: classpath:static/banner-docker.txt
  graphql:
    http:
      path: /api/v1/graphql
logging:
  file:
    name: backend.log
